// <auto-generated />
using HotelListing.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HotelListing.Migrations
{
    [DbContext(typeof(HotelListingDbContext))]
    partial class HotelListingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HotelListing.Data.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Germany",
                            ShortName = "DE"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Bulgaria",
                            ShortName = "BG"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Denmark",
                            ShortName = "DK"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Czechia",
                            ShortName = "CZ"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Belgium",
                            ShortName = "BE"
                        });
                });

            modelBuilder.Entity("HotelListing.Data.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "30, Mobolaji Bank Anthony Way, Airport Road, Ikeja GRA",
                            CountryId = 2,
                            Name = "Sheraton",
                            Rating = 4.5
                        },
                        new
                        {
                            Id = 2,
                            Address = "4, Onitolo Road, Off Gerrard Road",
                            CountryId = 1,
                            Name = "Wheatbaker",
                            Rating = 3.7000000000000002
                        },
                        new
                        {
                            Id = 3,
                            Address = "30, Mobolaji Bank Anthony Way, Airport Road, Ikeja GRA",
                            CountryId = 5,
                            Name = "Transcorp Hilton",
                            Rating = 4.6500000000000004
                        },
                        new
                        {
                            Id = 4,
                            Address = "5141, Aba Road, GRA Phase 2, Rumuadaolu",
                            CountryId = 2,
                            Name = "Hotel Presidential",
                            Rating = 4.0999999999999996
                        },
                        new
                        {
                            Id = 5,
                            Address = "10, Bisala Road, Independence Layout",
                            CountryId = 3,
                            Name = "Golden Royale",
                            Rating = 3.5
                        });
                });

            modelBuilder.Entity("HotelListing.Data.Hotel", b =>
                {
                    b.HasOne("HotelListing.Data.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });
#pragma warning restore 612, 618
        }
    }
}
